### Primeros pasos en Numpy

In [1]:

import numpy as np # linear algebra

In [2]:
a = np.array([2, 3, 8, 1, 0, 9])
a

array([2, 3, 8, 1, 0, 9])

In [3]:
b = np.arange(0,14,2)
b

array([ 0,  2,  4,  6,  8, 10, 12])

In [4]:
c = np.random.randint(0, 10, 8)
c

array([3, 4, 2, 3, 5, 8, 1, 7])

In [5]:
d = np.zeros(3)
d

array([0., 0., 0.])

In [6]:
d = np.zeros(3, dtype=int)
d

array([0, 0, 0])

In [7]:
e = np.ones(3, dtype=int)
e

array([1, 1, 1])

In [8]:
f = np.concatenate([d, e])
f

array([0, 0, 0, 1, 1, 1])

In [9]:
# "Modifying" arrays

b = np.delete(b, -2)
b

array([ 0,  2,  4,  6,  8, 12])

In [10]:
c = np.delete(c, [6,7])
c

array([3, 4, 2, 3, 5, 8])

In [11]:
d = np.append(c, [7, 5])
d

array([3, 4, 2, 3, 5, 8, 7, 5])

In [12]:
mask = d < 7
mask

array([ True,  True,  True,  True,  True, False, False,  True])

In [13]:
d = d[mask]
d

array([3, 4, 2, 3, 5, 5])

In [14]:
d[2] = 8
d

array([3, 4, 8, 3, 5, 5])

In [15]:
# Making matrix arrays

A = np.array([a,b,c])
A

array([[ 2,  3,  8,  1,  0,  9],
       [ 0,  2,  4,  6,  8, 12],
       [ 3,  4,  2,  3,  5,  8]])

In [16]:
print('matrix size = ' + str(A.size) + '\n')
print('matrix dimension = ' + str(A.ndim) + '\n')
print('matrix shape = ' + str(A.shape) + '\n')

matrix size = 18

matrix dimension = 2

matrix shape = (3, 6)



In [17]:
A[1][5] = 7
A[2, 3] = 1
A

array([[2, 3, 8, 1, 0, 9],
       [0, 2, 4, 6, 8, 7],
       [3, 4, 2, 1, 5, 8]])

In [18]:

A[2]

array([3, 4, 2, 1, 5, 8])

In [19]:
B = np.random.randint(0,10,18)
B.size

18

In [20]:
B = B.reshape(3,6)
B

array([[8, 9, 9, 8, 4, 2],
       [5, 5, 3, 7, 3, 5],
       [6, 8, 8, 0, 4, 6]])

In [21]:
C = B - 1
C

array([[ 7,  8,  8,  7,  3,  1],
       [ 4,  4,  2,  6,  2,  4],
       [ 5,  7,  7, -1,  3,  5]])

In [22]:
D = A + B
D

array([[10, 12, 17,  9,  4, 11],
       [ 5,  7,  7, 13, 11, 12],
       [ 9, 12, 10,  1,  9, 14]])

In [23]:
E = D / 2
E

array([[5. , 6. , 8.5, 4.5, 2. , 5.5],
       [2.5, 3.5, 3.5, 6.5, 5.5, 6. ],
       [4.5, 6. , 5. , 0.5, 4.5, 7. ]])

In [24]:
D = D.T
D

array([[10,  5,  9],
       [12,  7, 12],
       [17,  7, 10],
       [ 9, 13,  1],
       [ 4, 11,  9],
       [11, 12, 14]])

In [25]:
# Applying a function to each element in the n-dimensional array

toint = np.vectorize(lambda value: int(value))
E = toint(E)
E

array([[5, 6, 8, 4, 2, 5],
       [2, 3, 3, 6, 5, 6],
       [4, 6, 5, 0, 4, 7]])

In [26]:
# Where and Select functions

F = np.where(E < 5, -1, 1)
F

array([[ 1,  1,  1, -1, -1,  1],
       [-1, -1, -1,  1,  1,  1],
       [-1,  1,  1, -1, -1,  1]])

In [27]:
conditions = [(E < 5), (E == 5), (E > 5)]
values = [-1, 0, 1]
G = np.select(conditions, values)
G

array([[ 0,  1,  1, -1, -1,  0],
       [-1, -1, -1,  1,  0,  1],
       [-1,  1,  0, -1, -1,  1]])

In [28]:
# Saving data in files

np.save("E.npy",E)
np.savetxt("G.csv", G, fmt = '%i', delimiter=',')

# Restoring data from files

H = np.load("E.npy")
H

array([[5, 6, 8, 4, 2, 5],
       [2, 3, 3, 6, 5, 6],
       [4, 6, 5, 0, 4, 7]])

In [29]:
H in E

True

In [30]:
I = np.loadtxt("G.csv", dtype = int, delimiter = ',')
I

array([[ 0,  1,  1, -1, -1,  0],
       [-1, -1, -1,  1,  0,  1],
       [-1,  1,  0, -1, -1,  1]])

In [31]:
# Ordering data

J = np.random.randint(0,100,25)
J = J.reshape(5,5)
J

array([[20, 92, 95, 66, 32],
       [81, 25, 97,  7, 81],
       [13, 77,  9, 75, 24],
       [25, 74, 23, 48, 92],
       [61, 23, 70, 82, 67]])

In [32]:
J.sort(1)
J

array([[20, 32, 66, 92, 95],
       [ 7, 25, 81, 81, 97],
       [ 9, 13, 24, 75, 77],
       [23, 25, 48, 74, 92],
       [23, 61, 67, 70, 82]])

In [33]:
J.sort(0)
J

array([[ 7, 13, 24, 70, 77],
       [ 9, 25, 48, 74, 82],
       [20, 25, 66, 75, 92],
       [23, 32, 67, 81, 95],
       [23, 61, 81, 92, 97]])

In [34]:
J = J[::-1]
J

array([[23, 61, 81, 92, 97],
       [23, 32, 67, 81, 95],
       [20, 25, 66, 75, 92],
       [ 9, 25, 48, 74, 82],
       [ 7, 13, 24, 70, 77]])